# Generated by Django 2.2.8 on 2019-12-27 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jam1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=100)),
                ('jam_place', models.CharField(choices=[('Tienes un lugar para juntarse', 'Tienes un lugar para juntarse'), ('No tienes lugar para juntarse', 'No tienes lugar para juntarse')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('Amateur', 'Amateur'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado'), ('Profesional', 'Profesional')], max_length=30)),
                ('comment', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
