# Generated by Django 2.2.8 on 2020-02-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam1', '0003_auto_20200219_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instrument',
        ),
        migrations.AddField(
            model_name='profile',
            name='instruments',
            field=models.ManyToManyField(to='jam1.Instrument'),
        ),
    ]
