# Generated by Django 2.2.8 on 2020-02-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam1', '0004_auto_20200220_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='intereses',
            options={'ordering': ['Categoria', 'Nombre']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='event_suscribe',
            field=models.ManyToManyField(blank=True, to='jam1.Event'),
        ),
    ]
