# Generated by Django 2.2.8 on 2020-02-20 15:38

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('jam1', '0005_auto_20200220_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
