# Generated by Django 2.2.8 on 2020-02-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam1', '0006_auto_20200220_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Mendoza', max_length=255),
            preserve_default=False,
        ),
    ]
